apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - n8n.yaml
  - rustfs.yaml
  - monitoring.yaml
  - string-is.yaml
  - it-tools.yaml
  - s-pdf.yaml
  - uptime-kuma.yaml
  - homepage.yaml
  - ai-drawio.yaml
  - mcp-cloudflare.yaml
  - mcp-weather.yaml
  - mcp-airtable.yaml
  - excalidraw.yaml
  - miniflux.yaml
  - open-webui.yaml
  - rsshub.yaml
  - ai-workstation.yaml
  - www-delta-and-beta.yaml
  - www-delta-and-beta-image.yaml
  - www-delta-and-beta-automation.yaml
  - webhook-site.yaml
  - firecrawl.yaml
  - mcp-firecrawl.yaml
  - mcp-excalidraw.yaml
